### ISSUE TITLE
Error after scrape

### ISSUE THREAD

**Issue by Mac0r0ni** [sam5epi0l/BotTuber#4]
Hello, and thanks for your time making this. I'm having an issue. After its done scraping, i get the following error.

`Traceback (most recent call last):
  File "C:\DefenderExclude\YOUTUBECHANNLE\BotTuber\bottuber.py", line 326, in <module>
    attemptRoutine()
  File "C:\DefenderExclude\YOUTUBECHANNLE\BotTuber\bottuber.py", line 317, in attemptRoutine
    routine(title, description, tags)
  File "C:\DefenderExclude\YOUTUBECHANNLE\BotTuber\bottuber.py", line 180, in routine
    dfile.write(description)
  File "C:\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 446-450: character maps to <undefined>`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave

Any idea?

**Comment by sam5epi0l** [comment]
Reason: `charmap` supports `utf-8` encoding only. description variable contains an emoji.

The bug is resolved you can git clone to get latest version of BotTuber.(Not released as a package yet)
or you can just change description(remove emojis).
