### ISSUE TITLE
scrape_videos not working

### ISSUE THREAD

**Issue by lol20135** [sam5epi0l/BotTuber#8]
Hello sir i am newbie so plz guide me i am getting error and error again  if possible plz make a video on BotTuber 
ThankYou,. 

C:\Users\Hydra\Desktop\BotTuber-1.0-beta>python scrape_videos.py Starting Scraping Traceback (most recent call last): File "C:\Users\Hydra\Desktop\BotTuber-1.0-beta\scrape_videos.py", line 42, in <module> scrapeVideos(username = "chewymemes_v3", File "C:\Users\Hydra\Desktop\BotTuber-1.0-beta\scrape_videos.py", line 18, in scrapeVideos L.login(username, password) File "C:\Users\Hydra\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\instaloader.py", line 483, in login self.context.login(user, passwd) File "C:\Users\Hydra\AppData\Local\Programs\Python\Python310\lib\site-packages\instaloader\instaloadercontext.py", line 241, in login raise ConnectionException("Login error: \"{}\" status, message \"{}\".".format(resp_json['status'], instaloader.exceptions.ConnectionException: Login error: "fail" status, message "feedback_required".

**Comment by tiamica** [comment]
Make sure you are using Python 3.
