### ISSUE TITLE
Error Uploading Video to Youtube

### ISSUE THREAD

**Issue by tiamica** [sam5epi0l/BotTuber#9]
**Describe the bug**

[+] Uploading to Youtube...
Traceback (most recent call last):
  File "/Users/doncali/BotTuber/botTuber.py", line 335, in <module>
    attemptRoutine()
  File "/Users/doncali/BotTuber/botTuber.py", line 326, in attemptRoutine
    routine(title, description, tags)
  File "/Users/doncali/BotTuber/botTuber.py", line 288, in routine
    upload_to_youtube()
  File "/Users/doncali/BotTuber/botTuber.py", line 280, in upload_to_youtube
    uploadYtvid(VIDEO_FILE_NAME=outputFile,
  File "/Users/doncali/BotTuber/upload_ytvid.py", line 30, in uploadYtvid
    response_upload = googleAPI.videos().insert(
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/http.py", line 901, in execute
    _, body = self.next_chunk(http=http, num_retries=num_retries)
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 131, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/http.py", line 1021, in next_chunk
    raise ResumableUploadError(resp, content)
googleapiclient.errors.ResumableUploadError: <HttpError 400 when requesting None returned "The request metadata specifies an invalid video description.". Details: "[{'message': 'The request metadata specifies an invalid video description.', 'domain': 'youtube.video', 'reason': 'invalidDescription', 'location': 'body.snippet.description', 'locationType': 'other'}]">

**To Reproduce**
1. Execute botTuber 
2.[Q] Automated or Manual A/M:M
[Q] Type video title in 100 C or leave Blank to Use Default Title:]This is a Youtube test
[Q] Type video description headers or leave blank to use Default Headers:This is a test for BotTuber
[Q] Add some tags to default tag list or use default tags:This is a test
[+] Handling GoogleAPI
[+]  2022 4 22 2 18 58
[+]  ./APR_2022_v22.mp4
[+] Scraping Videos...
Starting Scraping

3. Error occurred when attempting to upload video

**Expected behavior**
Video is supposed to upload into Youtube account.

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Firefox
 

**Additional context**

**Comment by tiamica** [comment]
FIXED BY removing all the description and adding my own.
